### ISSUE TITLE
Demo broken since p2panda update `v0.8.0`

### ISSUE THREAD

**Issue by adzialocha** [p2panda/send-to-node#8]
I assume the document view id hashes given by JSON are wrongly interpreted as a string now but should be bytes?

**Comment by adzialocha** [comment]
https://github.com/p2panda/p2panda/pull/529

**Comment by sandreae** [comment]
We needed to update all the hash ids as they changed after using `v0.8.0`

https://github.com/p2panda/send-to-node/commit/eb718d9cacf21a235c8d234e1297fd3a435e509d
